"""
Merchant Report — One-page PDF digest for Razorpay merchants.

A weekly-digest-style summary pulling entirely from already-computed
evaluate.py and dashboard/business_impact.py output. No new calculations.

Distinct from engine/case_export.py's per-transaction audit PDF —
this is a portfolio-level summary a merchant would want in their inbox.
"""

import json
import os
import sys
from datetime import datetime, timezone

from fpdf import FPDF

# Reuse PDF helpers from case_export for consistent styling
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine.case_export import _sanitize, _section_header, _field_row
from engine.masking import tokenize_id


def generate_merchant_report(
    scored_df,
    classification_metrics: dict,
    recovery_metrics: dict,
    output_path: str,
) -> str:
    """Generate a one-page merchant report PDF.

    Args:
        scored_df: DataFrame with columns txn_id, amount, final_decision,
            band, raw_risk_score, true_label (the scored test set).
        classification_metrics: dict from evaluation_report.json["classification"].
        recovery_metrics: dict from evaluation_report.json["recovery"].
        output_path: where to write the PDF.

    Returns:
        output_path
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    total = classification_metrics.get("total_count", len(scored_df))

    # Determine final_decision: use column if present, else derive from band
    if "final_decision" in scored_df.columns:
        decision_col = scored_df["final_decision"]
    else:
        decision_col = scored_df["band"].map({
            "high_risk": "fraud",
            "safe": "legitimate",
            "ambiguous": "manual_review",
        })

    fraud_blocked_count = int(
        ((scored_df["true_label"] == True) & (decision_col == "fraud")).sum()
    )
    fraud_blocked_amount = round(
        float(scored_df[
            (scored_df["true_label"] == True) & (decision_col == "fraud")
        ]["amount"].sum()), 2
    )
    fp_count = classification_metrics.get("fp", 0)
    fp_rate = classification_metrics.get("false_positive_rate", 0.0)
    total_recovered = recovery_metrics.get("total_recovered", 0.0)
    recovery_rate = recovery_metrics.get("recovery_rate_pct", 0.0)
    manual_review_count = classification_metrics.get("manual_review_count", 0)
    manual_review_pct = classification_metrics.get("manual_review_pct", 0.0)

    # Top exceptions: highest-value blocked or manual_review cases
    exceptions = _get_top_exceptions(scored_df, n=5)

    # --- Build PDF ---
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, _sanitize("Sentinel -- Merchant Fraud Report"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    report_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 5, _sanitize(f"Report Date: {report_date}  |  Held-out test set: {total} transactions"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # --- Summary Metrics ---
    _section_header(pdf, "Summary")

    metrics = [
        ("Transactions Processed", f"{total}"),
        ("Fraud Cases Blocked", f"{fraud_blocked_count}  (INR {fraud_blocked_amount:,.2f})"),
        ("False Positives", f"{fp_count} customer(s)  ({fp_rate:.1%} rate)"),
        ("Revenue Recovered", f"INR {total_recovered:,.2f}  ({recovery_rate:.1f}% recovery rate)"),
        ("Manual Review Required", f"{manual_review_count} / {total}  ({manual_review_pct:.1%})"),
    ]
    for label, value in metrics:
        _field_row(pdf, label, value)

    # --- Top Exceptions ---
    if exceptions:
        _section_header(pdf, "Top Exceptions (Notable Cases)")

        # Table header
        pdf.set_font("Helvetica", "B", 8)
        col_widths = [35, 25, 30, 25, 75]
        headers = ["Case ID", "Amount", "Risk Score", "Decision", "Notes"]
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 5, _sanitize(h), border=0, new_x="END")
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        for exc in exceptions:
            row_data = [
                exc["case_id"],
                f"INR {exc['amount']:,.0f}",
                f"{exc['score']}",
                exc["decision"].replace("_", " ").title(),
                exc["note"],
            ]
            for i, val in enumerate(row_data):
                pdf.cell(col_widths[i], 5, _sanitize(str(val)), border=0, new_x="END")
            pdf.ln()

    # --- Footer ---
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 7)
    pdf.cell(
        0, 4,
        _sanitize("Generated by Sentinel -- AI Risk Manager + Revenue Recovery"),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.cell(
        0, 4,
        _sanitize("This report is based on a held-out test set. Production numbers will vary with actual transaction volume."),
        new_x="LMARGIN", new_y="NEXT",
    )

    pdf.output(output_path)
    return output_path


def _get_top_exceptions(scored_df, n=5):
    """Select the top N most notable exceptions (blocked or manual_review).

    Returns list of dicts with masked case_id, amount, score, decision, note.
    """
    # Determine final_decision: use column if present, else derive from band
    if "final_decision" in scored_df.columns:
        decision_col = scored_df["final_decision"]
    else:
        decision_col = scored_df["band"].map({
            "high_risk": "fraud",
            "safe": "legitimate",
            "ambiguous": "manual_review",
        })

    # Candidates: high_risk (blocked) + ambiguous that ended up manual_review
    candidates = scored_df[
        (scored_df["band"] == "high_risk") |
        (decision_col == "manual_review")
    ].copy()

    if len(candidates) == 0:
        return []

    # Sort by amount descending (highest-value cases first)
    candidates = candidates.sort_values("amount", ascending=False).head(n)

    exceptions = []
    for _, row in candidates.iterrows():
        case_id = tokenize_id(str(row["txn_id"]), prefix="TXN")
        amount = float(row["amount"])
        score = int(row["raw_risk_score"])
        decision = str(decision_col.loc[row.name])

        # Build a short note
        if row["band"] == "high_risk":
            note = f"Auto-blocked (score {score})"
        else:
            note = f"Sent to manual review (score {score})"

        if bool(row.get("in_detected_ring", False)):
            note += ", ring member"

        exceptions.append({
            "case_id": case_id,
            "amount": amount,
            "score": score,
            "decision": decision,
            "note": note,
        })

    return exceptions
